name: dart_code_writer
description: Helpers for dart generators that make dart code generation easier.
version: 0.0.3
homepage: https://github.com/nivisi/dart_code_writer
repository: https://github.com/nivisi/dart_code_writer

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
